["TeamName1".Filmoteka]
team = [
    "Tomasz Mazur*",
    "Artur Krasniewski",
    "Joanna Golofit",
    "Damian Brzezinski"
]

["TeamName2".EventBooster]
team = [
    "Kamil Witkowski*",
    "Szatkowski Pawel",
    "Przemyslaw Kaminski",
    "Michal Dziuba"
]

["Clean Code Squad".Filmoteka]
team = [
    "Tomasz Sokol*",
    "Sebastian Hanusiak",
    "Bielicki Michal",
    "Patrycja Nowakowska"
]

["TeamName3".Filmoteka]
team = [
    "Karolina Scieszko*",
    "Grzegorz Hamala",
    "Jakub Beltowski",
    "Bartosz Swiderski"
]

["Team work"]
team = ["Leader + Scrum Master", "JS", "JS", "HTML/CSS/JS"]
# 5. API documentation
# 4x API call (GET)
# 2x API call (Trending, Searched)
# 2x API call (Genres, One Movie)
# [Filmoteka]
# 1. LocalStorage:
#   1. TrendingMovies (incl. pages) (1 API call)
#   2. SearchedMovies (incl. pages) (multiple API calls)
#   3. Movie (multiple API calls)
#   4. Genres (1 API call)
#   5. TeamMembers [read-only]
